#remote_theme: pages-themes/modernist@v0.2.0
remote_theme: peterdesmet/petridish@3.1
plugins:
    - jekyll-remote-theme # add this line to the plugins list if you already have one
title: PRIN PROJECT - SAFEST
description: Trust assurance of Digital Twins for medical CPSs
