#remote_theme: pages-themes/modernist@v0.2.0
remote_theme: peterdesmet/petridish@3.1
plugins:
    - jekyll-remote-theme # add this line to the plugins list if you already have one
title: PROGETTO PRIN - SAFEST Trust assurance of Digital Twins for medical CPSs
description: [description]

# THEME SETTINGS (ALL OPTIONAL)
posts_on_home: 2                        # Show x number of latest posts on homepage, can be 0
archive_permalink: /news/               # Permalink of page using the archive.html layout, required when using post tags
github_edit: true                       # Show an "edit this page" link in the footer, can also be name of branch (default: main)

social:
  email: name@example.com
  twitter: twitter_username
